Level one assets
Guysus/SteveSloth pull request #104
Opened 2024-05-09 01:01 UTC by Guysus

added ground surface, rocks and debris, bushes and large cliff rocks.
The tree package will be able to use on all the levels

2024-05-09 01:10 UTC, Saretzky requested changes
there a a lot of assets, are they all necessary for level 1. and there's a conflict

2024-05-09 01:21 UTC, Saretzky requested changes
looking at this more there are definitely unnecessary assets in here. be sure you only inlude things we are using for level 1 specifically

2024-05-09 01:21 UTC, Saretzky commented on Config/DefaultEngine.ini
why are you changing the default map to level 1?

2024-05-09 22:12 UTC, Saretzky requested changes
honestly, i would start from scratch, and only add in exactly what will be used for level 1 and nothing more. if the tree has a huge amount of assets, maybe find a more simple tree. 566 assets is too many

2024-05-10 01:09 UTC, Saretzky requested changes
Also, make sure everything is in the artwork folder

2024-05-10 01:09 UTC, Saretzky commented on Content/LevelAssets/Trees_Assets_ForAllLevels/Meshes/SM_SK_Mannequin1.uasset
remove this

2024-05-10 01:09 UTC, Saretzky commented on Season_trees_VOL_1.png
remove this

2024-05-10 18:37 UTC, Saretzky requested changes
look at the msPresets folder, move and rename, or delete what is unnecessary (Season_Trees_VOL1/Materials folder also). 

there is still a lot to rename in the Trees_Assets_ForAllLevels folder especially in the LOD, GLF, LF, and Luts folders

2024-05-10 18:37 UTC, Saretzky commented on Season_trees_VOL_1.png
remove this

2024-05-11 01:20 UTC, AMacLeod99 approved these changes

2024-05-12 01:42 UTC, Saretzky requested changes
there are still many things that need to be renamed, I marked some, but most of the assets in the materials folder in the trees for all levels folder, and the assets in the foliage material folder

2024-05-12 01:42 UTC, Saretzky commented on Content/Season_trees_VOL1/Materials/M_ST_Inst.uasset
rename and move this, or delete this

2024-05-12 01:42 UTC, Saretzky commented on Season_trees_VOL_1.png
delete this

2024-05-12 01:42 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Luts/T_Lt_otm.uasset
Rename this

2024-05-12 01:42 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Luts/T_Nolf.uasset
Rename this

2024-05-12 01:42 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Luts/T_otm_c.uasset
Rename this

2024-05-12 01:42 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Luts/T_smr_c.uasset
Rename this

2024-05-13 21:07 UTC, Saretzky requested changes
change name for all files indicated and delete files indicated (since there are many review comments, you might need to expand it to see the full list). 

also, rename all the assets in the Trees_Assets_ForAllLevels/Textures/LODs folder

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/M_White.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Detail_Normal.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Global_Wind.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Imposter.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_World_Normal.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Grouped_Leaves_Textures/T_Colourvar_ss.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Season_trees_VOL1/Materials/M_ST_Inst.uasset
delete, or rename and move this

2024-05-13 21:07 UTC, Saretzky commented on Season_trees_VOL_1.png
delete this

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/T_Default_Material.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/T_Detail_1.uasset
Rename this to be more descriptive

2024-05-13 21:07 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/T_Noise.uasset
Rename this to be more descriptive

2024-05-14 06:45 UTC, Saretzky requested changes

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Grouped_Leaves_Textures/T_Colourvar_ss.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_yl.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_sscolor_1.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_sscolor.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_snow.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_or.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_grn.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_gr.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_Glf_Normals.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Leaf_Textures/T_GL_RGB_Mask.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Grouped_Leaves_Textures/T_Yell_brunch_leaf.uasset
change brunch to branch

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Color_Bars_Textures/T_Color_Bar_smr_c.uasset
is this necessary?

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Color_Bars_Textures/T_Color_Bar_otm_c.uasset
is this necessary?

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Color_Bars_Textures/T_Color_Bar_otm.uasset
is this necessary?

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Textures/Color_Bars_Textures/T_Color_Bar_Nolf.uasset
is this necessary?

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_World_Normal.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Imposter.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Global_Wind.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MaterialFunction/MF_Detail_Normal.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/M_White.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/M_Stripe.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MI_Stripe_02.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/MI_Stripe_01.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/Trees_Assets_ForAllLevels/Materials/LODs/M_tl_yell_LOD.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/M_MS_Surface_Material.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/Functions/MF_Transmission.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/Functions/MF_Tiling.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/Functions/MF_ObjAdjustments.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/Functions/MF_MapAdjustments.uasset
change

2024-05-14 06:45 UTC, Saretzky commented on Content/Artwork/LevelAssets/LevelOneAssets/Ground_Surfaces/Surface_Material/Functions/MF_Displacement.uasset
change

2024-05-14 12:11 UTC, Jeff-Moreau requested changes
This branch has conflicts with Hub.. needs to be fixed otherwise cant merge.
Also honestly there is too much in the branch.. break it up make it easier to follow

2024-05-14 23:11 UTC, Saretzky approved these changes
looks good

2024-05-14 23:12 UTC, Jeff-Moreau approved these changes
looks good

2024-05-14 23:18 UTC, merged