More states
Guysus/SteveSloth pull request #108
Opened 2024-05-10 01:39 UTC by Jeff-Moreau

Lots to take in here.. Created all Generic States to be used or copied for more advanced states. Lots of edits to baseclass basestate and statemachine

2024-05-10 01:49 UTC, MysticAmazon approved these changes
Everything Seems good

2024-05-10 01:50 UTC, Saretzky requested changes

2024-05-10 01:50 UTC, Saretzky commented on Content/Blueprints/TestEnemy.uasset
remove test enemy

2024-05-10 01:56 UTC, Jeff-Moreau commented on Content/Blueprints/TestEnemy.uasset
Fine

2024-05-11 01:23 UTC, AMacLeod99 approved these changes

2024-05-13 21:14 UTC, merged