Level four assets
Guysus/SteveSloth pull request #112
Opened 2024-05-11 00:40 UTC by Guysus

City building, coral, wet soil, yellow and green grass

2024-05-11 01:01 UTC, AMacLeod99 approved these changes

2024-05-11 01:59 UTC, CrazyTobi approved these changes
Looks good

2024-05-12 01:35 UTC, Saretzky requested changes
you're importing the ms presets again

2024-05-13 20:04 UTC, Guysus commented
Good catch Elad, I deleted the MSPreset folder

2024-05-13 20:46 UTC, Saretzky requested changes
add the name of the asset to all the files indicated (eg. Seaweed)

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Seaweed/Foliage_Material/Functions/MF_Translucency.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Seaweed/Material/M_MS_Billboard_Material.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Displacement.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_MapAdjustments.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_ObjAdjustments.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Tiling.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Transmission.uasset
Rename this to be more descriptive

2024-05-13 20:46 UTC, Saretzky commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/M_MS_Surface_Material.uasset
Rename this to be more descriptive

2024-05-14 01:26 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Seaweed/Foliage_Material/Functions/MF_Translucency.uasset
done

2024-05-14 01:26 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Seaweed/Material/M_MS_Billboard_Material.uasset
done

2024-05-14 01:26 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Displacement.uasset
done

2024-05-14 01:31 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_MapAdjustments.uasset
done

2024-05-14 01:31 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_ObjAdjustments.uasset
done

2024-05-14 01:31 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Tiling.uasset
done

2024-05-14 01:31 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/Functions/MF_Transmission.uasset
done

2024-05-14 01:32 UTC, Guysus commented on Content/Artwork/LevelAssets/Level_Four_Assets/Surfaces/Surface_Material/M_MS_Surface_Material.uasset
done

2024-05-14 12:08 UTC, Jeff-Moreau requested changes
This branch has Hub conflicts.. Please fix.. cant merge otherwise

2024-05-14 15:17 UTC, Jeff-Moreau approved these changes
Looks Good

2024-05-14 15:17 UTC, merged