Level one map editing
Guysus/SteveSloth pull request #158
Opened 2024-05-17 18:48 UTC by Guysus

Cave, Desert, Beach and forest area

2024-05-17 19:36 UTC, Saretzky requested changes
What is all the added files in the _ExternalActors_ folder? is it necessary to merge?

fix the flat rocks
![image](https://github.com/Guysus/SteveSloth/assets/129458993/2d203a15-bcd0-48b1-b766-b0844606d271)

add normal map to the sand beach texture, it looks too flat. and instead of using a plane with the texture on it, paint the landscape with the material.

Blend the transition between biomes (make it look less drastic, the beach is very harsh but the transition between the other 2 biomes need to be blended more)
![image](https://github.com/Guysus/SteveSloth/assets/129458993/08d2184a-a668-44ca-9be1-2f5b5cd8a961)

add more details in this biome (rocks, grass, plants etc)
![image](https://github.com/Guysus/SteveSloth/assets/129458993/003c2e46-30bd-477b-8ab5-e7c56ce41ef3)

2024-05-17 19:41 UTC, Saretzky requested changes
also the transition between the water and land need to be worked on 
![image](https://github.com/Guysus/SteveSloth/assets/129458993/339a4a97-8a53-40cd-aac3-71b8d0df9a8e)

2024-05-17 20:10 UTC, Jeff-Moreau requested changes
Truthfully dont know what to say, we can discuss in class

2024-05-19 02:53 UTC, Saretzky requested changes
review if whats done so far: theres still a lot of the above changes that needs to be done

2024-05-22 22:30 UTC, Saretzky requested changes
MSPresets folder showed up again

the water to beach needs some work, the line between them is too harsh
![image](https://github.com/Guysus/SteveSloth/assets/129458993/53c40d32-3e7f-43fd-b133-74ac7f471bd6)
 
move everything up or add a proper sky box so we cant see the black void when looking at horizon
![image](https://github.com/Guysus/SteveSloth/assets/129458993/20528b2b-f291-41b9-bf05-9931e62e0ca9)

dont use a plain with a material on it for this. it looks stretched and flat
![image](https://github.com/Guysus/SteveSloth/assets/129458993/b7e3a596-a69d-4125-ac57-48b3a3f64a1c)

same with this area
![image](https://github.com/Guysus/SteveSloth/assets/129458993/1a8d0ebd-a075-4993-ad54-4776a9491dec)

there's no grass/something to fill out this area
![image](https://github.com/Guysus/SteveSloth/assets/129458993/a192873f-989e-4a3b-ba78-f64dbeba65db)

what happened to the lighting in the cave?
![image](https://github.com/Guysus/SteveSloth/assets/129458993/4b76f5fd-9979-474d-977d-eb0d12d01a7c)

2024-05-24 01:21 UTC, AMacLeod99 approved these changes

2024-05-24 01:35 UTC, Saretzky requested changes
can we put these assets in a folder
![image](https://github.com/Guysus/SteveSloth/assets/129458993/14f3d509-72b4-4bfa-ab18-64b1f0a15664)

keep the level manager outside of a folder, just assets
![image](https://github.com/Guysus/SteveSloth/assets/129458993/a43b9eb3-c3be-4c9a-80a8-21ac5f437434)

2024-05-24 01:35 UTC, Saretzky requested changes

2024-05-24 01:35 UTC, Saretzky commented on Config/DefaultEngine.ini
change this back to hub

2024-05-24 02:06 UTC, Jeff-Moreau approved these changes
Looks Good

2024-05-24 02:13 UTC, Saretzky approved these changes
fixed some small stuff myself, good to go

2024-05-24 02:29 UTC, merged