Water Balloon Ammo/ Confusion State
Guysus/SteveSloth pull request #173
Opened 2024-05-22 02:08 UTC by CrazyTobi

Created data table row and blueprint for the water balloon also updated code to incorporate the confusion state, please let me know how it is and if I missed anything, didn't add logic for the confusion figured that could be its own task but worked on adding the basics at least

2024-05-22 02:33 UTC, Saretzky requested changes

2024-05-22 02:33 UTC, Saretzky commented on Source/SteveSloth/Private/MyGenericEnemyConfusionState.cpp
Add some more unique behavior in this state, maybe wandering randomly or something

2024-05-23 01:05 UTC, Saretzky requested changes

2024-05-23 01:05 UTC, Saretzky commented on Source/SteveSloth/Public/MyGenericEnemyConfusionState.h
> +	float MaxConfusionRange;
make this a Uproperty in the enemy data

2024-05-23 11:06 UTC, Saretzky commented
I did various fixes, and I know why it's not working and how to fix it. Gonna figure out how to write what is missing

2024-05-25 00:01 UTC, Jeff-Moreau requested changes
Other than what I wrote looks good.. Love the Vinterp nice

2024-05-25 01:50 UTC, merged