Grappling hook pickup
Guysus/SteveSloth pull request #213
Opened 2024-05-24 19:56 UTC by Guysus

2024-05-24 20:04 UTC, Saretzky requested changes
3 questions:
1. Is part of the task to add functionality, or is it just the pickup?
2. Has this been tested?
3. is there a grapple input action and set up in the IMC?

2024-05-24 20:24 UTC, Guysus commented
> 3 questions:
> 
>     1. Is part of the task to add functionality, or is it just the pickup?
> 
>     2. Has this been tested?
> 
>     3. is there a grapple input action and set up in the IMC?

I think it's just for the pick up, but I was setting up to functions to call.

2024-05-24 20:35 UTC, Saretzky commented
> > 3 questions:
> > ```
> > 1. Is part of the task to add functionality, or is it just the pickup?
> > 
> > 2. Has this been tested?
> > 
> > 3. is there a grapple input action and set up in the IMC?
> > ```
> 
> I think it's just for the pick up, but I was setting up to functions to call.

what about questions 2 and 3

2024-05-24 20:40 UTC, Guysus commented
> > > 3 questions:
> > > ```
> > > 1. Is part of the task to add functionality, or is it just the pickup?
> > > 
> > > 2. Has this been tested?
> > > 
> > > 3. is there a grapple input action and set up in the IMC?
> > > ```
> > 
> > 
> > I think it's just for the pick up, but I was setting up to functions to call.
> 
> what about questions 2 and 3

I will deleted the input stuff and put it in the player ability branch, then I will test this pick up

2024-05-26 02:03 UTC, Saretzky requested changes
is it working when tested?

2024-05-26 02:03 UTC, Saretzky commented on Source/SteveSloth/Private/MyPlayer.cpp
> +	UE_LOG(LogTemp, Warning, TEXT("Add Grappling Hook"));
remove testing stuff

2024-05-26 02:03 UTC, Saretzky commented on Source/SteveSloth/Private/ItemBaseClass.cpp
> +				UE_LOG(LogTemp, Warning, TEXT("Overlap Grappling Hook"));
remove testing stuff

2024-05-26 02:04 UTC, Jeff-Moreau commented
> is it working when tested?

Nope is having issues with the mesh showing up in game.. the collision is working well though

2024-05-26 02:48 UTC, Saretzky commented
> > is it working when tested?
> 
> Nope is having issues with the mesh showing up in game.. the collision is working well though

I think i solved it, just testing right now

2024-05-26 02:57 UTC, Saretzky approved these changes
looks good

2024-05-26 03:33 UTC, Jeff-Moreau approved these changes
Looks Good thank you elad

2024-05-26 03:34 UTC, merged