Player upgrade abilities
Guysus/SteveSloth pull request #222
Opened 2024-05-27 17:10 UTC by Guysus

2024-05-27 17:36 UTC, Saretzky requested changes
according to the trello card this task requires for actual functionality of the mechanics, rather than empty functions

2024-05-27 17:36 UTC, Saretzky commented on Source/SteveSloth/Private/MyPlayer.cpp
> +			UE_LOG(LogTemp, Warning, TEXT("Grappling Time!!"))
get rid of testing stuff

2024-05-27 17:36 UTC, Saretzky commented on Source/SteveSloth/Private/MyPlayer.cpp
> +		// USE TIMER TO RESET GRAPPLING HOOK
add the timer

2024-05-27 17:52 UTC, Jeff-Moreau requested changes

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> +
All of these from 146 to 170 should just be a list of upgradeable items that one function will check if the item is unlocked or not

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> +
we are never going to use all the functions at the same time. So the functions should not have their own input, should just be one input with a switch state inside it that calls the function based off of which upgrade is being used at that time.

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> +			UE_LOG(LogTemp, Warning, TEXT("Grappling Time!!"))
> get rid of testing stuff

agree

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> +		// USE TIMER TO RESET GRAPPLING HOOK
> add the timer

agree

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> +
all these functions need to have functionality in them. As stated above these functions should be called from within a switch statement based on which upgrade is currently active.

2024-05-27 17:52 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyPlayer.h
> +	UInputAction* PMagnetic;
we are never going to use all the functions at the same time. So the functions should not have their own input, should just be one input with a switch state inside it that calls the function based off of which upgrade is being used at that time.

2024-05-28 02:04 UTC, Saretzky requested changes
there's still a lot that needs to get done, but here are some minor preliminary reviews. right now this is still a barebones skeleton and there needs actual functionality

2024-06-06 15:15 UTC, Saretzky requested changes
get rid of print screen in the switch ability (maybe have some sort of UI element that shows what ability)
![image](https://github.com/Guysus/SteveSloth/assets/129458993/292ca1f7-8ec6-4000-832e-bf5a331371f6)

2024-06-06 15:15 UTC, Saretzky commented on Source/SteveSloth/Public/MyBaseDestructibleObject.h
why is this commented out?

2024-06-06 15:15 UTC, Saretzky commented on Source/SteveSloth/Private/MyBaseDestructibleObject.cpp
Whys is this commented out?

2024-06-06 15:15 UTC, Saretzky commented on Source/SteveSloth/Public/MyPlayer.h
> +	EAbility Ability;
are we using this variable?

2024-06-06 15:15 UTC, Saretzky commented on Source/SteveSloth/Public/MyItemData.h
> -	GrapplingHook UMETA(DisplayName = "Grappling Hook")
why are we removing these?

2024-06-06 15:15 UTC, Saretzky commented on Source/SteveSloth/Public/MyPlayer.h
> +	void SetCurrentHealth(float amount) { CurrentHealth = CurrentHealth + amount; }
move the getters and setters back to right above the constructor

2024-06-06 15:15 UTC, Saretzky commented
> get rid of print screen in the switch ability (maybe have some sort of UI element that shows what ability) ![image](https://private-user-images.githubusercontent.com/129458993/337325325-292ca1f7-8ec6-4000-832e-bf5a331371f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcyMDUsIm5iZiI6MTcxNzY4NjkwNSwicGF0aCI6Ii8xMjk0NTg5OTMvMzM3MzI1MzI1LTI5MmNhMWY3LThlYzYtNDAwMC04MzJlLWJmNWEzMzEzNzFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNTE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjNmMjM0YThjNjc0ODA3MzcxNDIxZjI3YzQzYmMyOGFjY2VkZTM0NjZhZTY4YWU4MmNiMTA2ZjViMGY2NTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A7CFcvu0VQEHPw8L-8V9KLGNOulq7SaZ8PWX0v7hQoA)

you can use the player hud blueprint

2024-06-06 15:47 UTC, Jeff-Moreau requested changes
this is to start.. i need to load your branch

2024-06-06 15:47 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyPlayer.h
> -#include "MyLevelManager.h"
put back in, should not be removed

2024-06-06 17:57 UTC, Jeff-Moreau requested changes
![image](https://github.com/Guysus/SteveSloth/assets/119882736/1ac692c8-213d-4f5e-ab9e-e4421b66d62a)
All this needs to be fixed

2024-06-06 17:57 UTC, Jeff-Moreau commented
You removed all crates out of the game.. they need to be put back

2024-06-06 18:00 UTC, Jeff-Moreau commented
Swimming does not work, the colliders you put in place are missing

2024-06-06 18:26 UTC, Jeff-Moreau requested changes

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> -	LevelManager = AMyLevelManager::GetInstance();
put this back it is needed

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyPlayer.cpp
> -
Whys is this removed?

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyBaseClass.h
> +	bool bIsCurrentlyConfused;
I understand what you were doing here.. but you were suppose to be working on the player not organizing other code.. things like this mess up code.. stick to what you were doing..

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyItemData.h
> -	GrapplingHook UMETA(DisplayName = "Grappling Hook")
This messed up the BP_objects as well they are now missing materials.. again if not needed to touch for your task please dont

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyPlayer.h
> +	UInputAction* PCamPitch;
There was already a pitch input, what was the purpose of adding another?

2024-06-06 18:26 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyPlayer.h
> +	FVector WallHitLocation;
I dont see where these three variables are used.. if they are cool, if not please remove

2024-06-07 01:32 UTC, Saretzky approved these changes
looks good

2024-06-07 01:33 UTC, merged