Opening level one boss cutscene
Guysus/SteveSloth pull request #245
Opened 2024-05-31 02:34 UTC by CrazyTobi

Still needs clean up but just want to make sure the video is good so I'm posting it for review just so if there are any changes other then clean up I don't have to remake everything

2024-05-31 02:38 UTC, Saretzky requested changes
add audio

2024-05-31 23:53 UTC, CrazyTobi commented
> add audio

Done!

2024-06-01 00:34 UTC, Jeff-Moreau approved these changes
Looks Good

2024-06-01 01:31 UTC, AMacLeod99 approved these changes

2024-06-01 01:39 UTC, merged