my enemy AI dead state
Guysus/SteveSloth pull request #72
Opened 2024-04-30 00:55 UTC by Guysus

2024-04-30 01:06 UTC, AMacLeod99 requested changes
The script line in the copyright is incorrect, it says ItemBaseClass.

2024-04-30 01:33 UTC, Jeff-Moreau requested changes
This is just initial thoughts.. Im sure there is other things.. We can check more as you go.

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> + * Script: ItemBaseClass
Wrong class written here Should be the name of the class you are working on

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> +	isDead = false;
This variable name does not conform to the standards in the examples
Should be IsDead with a capital I

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> +MyEnemyAIDeadState::~MyEnemyAIDeadState()
This function is not needed and should be removed

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> +void MyEnemyAIDeadState::DeadAnimation()
1: This function is never called.
2: This function should execute some commands or have functionality to actual change the animation of the enemy to its dead animation.
3: you should code in a count down timer to start once the animation is done playing.
Theses are some of the things that i would put into this function

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> +void MyEnemyAIDeadState::DropItem()
1: This function is never called.
2: this function should chose from a list of items that the specific enemy inheriting this class will drop.
3: then it should instantiate that item in the game at the location of the enemy.
Again these are some things that i would put in here.

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIDeadState.h
> +	bool isDead;
This is named wrong and should be IsDead with a capitol I

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIDeadState.cpp
> +MyEnemyAIDeadState::MyEnemyAIDeadState()
In the constructor is where you should be calling your functions. This constructor is called when the StateMachine first calls this class.
This is the starting point of where the code needs to start and function.

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIDeadState.h
> +//#include "MyEnemyAIDeadState.generated.h"
Commented out code should be removed unless otherwise needed.

2024-04-30 01:33 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIDeadState.h
> +	~MyEnemyAIDeadState();
This is not needed and should be removed

2024-05-05 02:04 UTC, Saretzky requested changes

2024-05-05 02:04 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyDeadState.cpp
move the timer to the enter state function, might not need the bool if you do it that way. 

Very important: Be sure to test it.

2024-05-05 02:04 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyDeadState.h
> +	AMyEnemyBaseClass* Enemy;
does this need to be public

2024-05-05 18:26 UTC, Saretzky requested changes

2024-05-05 18:26 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyDeadState.h
> +	AMyEnemyBaseClass* Enemy;
Also, this is just getting a reference to the script, you need to get a reference to the actual enemy

2024-05-05 18:26 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyDeadState.cpp
> +		//Drop Item
these need to be called before the timer is called

2024-05-05 18:27 UTC, Saretzky requested changes

2024-05-05 18:27 UTC, Saretzky commented on Content/Levels/Hub.umap
dont need to include this in the pull request

2024-05-10 00:01 UTC, Saretzky requested changes

2024-05-10 22:11 UTC, AMacLeod99 approved these changes

2024-05-12 19:21 UTC, Saretzky approved these changes
be sure to update from main, then you're good to go

2024-05-13 19:15 UTC, merged