Enemy AI Idle State
Guysus/SteveSloth pull request #73
Opened 2024-04-30 01:04 UTC by AMacLeod99

2024-04-30 01:35 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIIdleState.cpp
> +#include "MyEnemyAIIdleState.h"
Need to remove all whitespaces from the code to keep it inline and easy to read

2024-04-30 01:35 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIIdleState.cpp
> +MyEnemyAIIdleState::~MyEnemyAIIdleState()
This is not needed should be removed

2024-04-30 01:38 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAIIdleState.cpp
> +void MyEnemyAIIdleState::DetectPlayer()
1: This function is never called.
2: Should write the code to detect the player.
3: should setup a range to detect the player in, 100 units away 1000 units away. These things need to be used and adjusted.
4: If no player around for X amount of time go into patrol state
5: If player in range start to chase player.

2024-04-30 01:38 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> + */
These three comment lines should be removed.. pay attention to white spaces

2024-04-30 01:38 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +
whitespaces not needed

2024-04-30 01:39 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +UCLASS()
For the entirety of the header file.. please follow the template that was put in chat.. including comments for sections

2024-04-30 01:40 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +	~MyEnemyAIIdleState();
This should be removed it is not needed

2024-04-30 01:41 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +	void DetectPlayer();
Should be a lot more than a detectplayer function.
Needs to play an idle animation
Needs a count timer to go into patrol mode.
Needs to know where the enemy was spawned in, create a vector and add its initial location to it.
this way it knows where it started and where to go back to.

These are just some ideas.. Im sure there is more. but it is a start

2024-05-01 22:24 UTC, Saretzky requested changes

2024-05-01 22:24 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +	bool HasDetectedPlayer;
rename to IsPlayerDetected
and maybe write a getter for this variable depending on how you're planning on swapping states

2024-05-01 22:24 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyAIIdleState.cpp
> +void AMyEnemyAIIdleState::DetectPlayer()
fill out logic for the function

2024-05-01 22:24 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyAIIdleState.h
> +	void BeginChase();
not sure this function is necessary (ie. this will trigger the chase state/change the detected bool in the DetectPlayer())

2024-05-01 23:55 UTC, Saretzky requested changes
Right now there isnt something detecting  when it should change to patrolling state vs when it should change to chasing state. you're lumping them both together when they have 2 different aspects

2024-05-02 02:30 UTC, Saretzky requested changes
a bit confused, will ask for clarification next class

2024-05-04 01:21 UTC, closed without merging