Enemy ai attacking state
Guysus/SteveSloth pull request #90
Opened 2024-05-07 02:08 UTC by Kenster833

Alright, its up for review. Rip it apart and let me know, I want to get this right

2024-05-07 12:18 UTC, Jeff-Moreau requested changes

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +bool UMyEnemyAttackingState::IsPlayerInRange() const
Dont need to check range that is/will be done in the state machine. This script should be what happens when the enemy is attacking. I would remove the whole function. Just wondering as to why this function is const?

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +{
This Attack player does not attack the player... There should be combat in here, interaction with the player, playing animations, doing damage to the player. Things of that sort.

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +	ACharacter* PlayerCharacter = UGameplayStatics::GetPlayerCharacter(GetWorld(), 0);
If you were listening in class this is not how we get access to the player.. Please follow what we did in class.. there is also some examples in chat in class.. and i shared my screen to show how as well..

add
ACharacter* Player; to the Header file

then add
Player = USteveSingleton::GetSteve()->GetPlayerCharacter(); to the Enter state of the cpp

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAttackingState.h
> +/**
these empty comments should not be here.. please clean up the code and indent properly

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Public/MyEnemyAttackingState.h
> + * Description: Enemy Attack State
Describe in more depth what this state does please

2024-05-07 12:18 UTC, Jeff-Moreau commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> + * Description: Enemy Attack State
Describe in more depth what this state does please

2024-05-07 14:41 UTC, Saretzky requested changes
Try testing by putting this into the component like we did in class yesterday. might even be worth splitting up the TArray in the component to have 1 (or array) for melee, range, and both

2024-05-07 14:41 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyAttackingState.h
> +UCLASS()
make this UCLASS(Blueprintable)

2024-05-07 14:41 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +#include "Kismet/GameplayStatics.h"
includes should be in the header

2024-05-07 14:41 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +#include "MyEnemyBaseClass.h"
This will cause circular inclusion problems, you might want to put the attack variables from the base class in this script.

2024-05-07 23:47 UTC, Kenster833 commented
This is the start of reviewing version 2

2024-05-08 00:17 UTC, Saretzky requested changes
Might be worthwhile having 2 scripts, 1 melee attack state, 1 range attack state. Melee will handle dealing the damage to the player & animation, while range will just spawn the projectile. ignore all attack ranges, that will be done in the enemy class, since it's dealing with switching the states

2024-05-08 00:17 UTC, Saretzky commented on Source/SteveSloth/Private/MyEnemyAttackingState.cpp
> +        if (Distance < Owner->GetAttackRange())
dong bother with any of the attack range stuff

2024-05-09 01:14 UTC, Saretzky requested changes
Make 2 scripts, 1 melee attack state, 1 range attack state. Melee will handle dealing the damage to the player & animation, while range will just spawn the projectile. have cooldowns on both

2024-05-09 01:14 UTC, Saretzky commented on Source/SteveSloth/Public/MyEnemyBaseClass.h
> +	float GetAttackRange() const { return AttackRange; }
dont bother with this for now, that will be done in a different task

2024-05-13 23:57 UTC, closed without merging